name: Force color
description: Set environment variables to force terminal color output
author: Ville Skyttä

runs:
  using: composite
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        {
          # General
          echo FORCE_COLOR=1             # https://force-color.org
          echo CLICOLOR_FORCE=1          # https://bixense.com/clicolors/

          # Rust
          echo CARGO_TERM_COLOR=always   # https://doc.rust-lang.org/cargo/reference/config.html#termcolor
          echo RUSTUP_TERM_COLOR=always  # https://rust-lang.github.io/rustup/environment-variables.html#environment-variables
        } >>"$GITHUB_ENV"
